In [18]:
# Aggregate analysis using groupby
import pandas as pd
df = pd.read_csv(r'C:\Users\16254\Desktop\numpy & pandas\English Premier League.csv')
print(df.head(), '\n')

# Select only numeric columns before calculating the mean
numeric_columns = df.select_dtypes(include = ['number']).columns

# Group by HomeTeam and mean numeric_columns
grouped_df = df.groupby(['HomeTeam'])[numeric_columns].mean()
print(grouped_df, '\n')

# Group by HomeTeam and sum HomeGoals, then sort by HomeGoals in descending order
grouped_df2 = df.groupby(['HomeTeam'])['HomeGoals'].sum().sort_values(ascending=False)
print(grouped_df2, '\n')

# Add a 'count' column to count the number of rows per HomeTeam
df['count'] = 1  #Adds a column named 'count' filled with 1 for each row. This will allow you to count the number of rows for each group (i.e., how many matches each HomeTeam had).
grouped_df3 = df.groupby(['HomeTeam'])['count'].sum()
print(grouped_df3, '\n')
# This is good way to track how many times an event occurs in your dataframe.

                   League      Date     HomeTeam        AwayTeam  HomeGoals  \
0  English Premier League  14/08/93      Arsenal        Coventry          0
1  English Premier League  14/08/93  Aston Villa             QPR          4
2  English Premier League  14/08/93      Chelsea       Blackburn          1
3  English Premier League  14/08/93    Liverpool  Sheffield Weds          2
4  English Premier League  14/08/93     Man City           Leeds          1

   AwayGoals Result
0          3      A
1          1      H
2          2      A
3          0      H
4          1      D

                  HomeGoals  AwayGoals
HomeTeam
Arsenal            2.059233   0.860627
Aston Villa        1.317215   1.125725
Barnsley           1.315789   1.842105
Birmingham         1.218045   1.052632
Blackburn          1.550459   1.110092
Blackpool          1.578947   1.947368
Bolton             1.291498   1.267206
Bournemouth        1.368421   1.543860
Bradford           1.210526   1.526316
Brentford          1.500000   1.026316
Brighton           1.236842   1.280702
Burnley            1.059211   1.282895
Cardiff            1.078947   1.921053
Charlton           1.309211   1.302632
Chelsea            1.937282   0.839721
Coventry           1.217949   1.096154
Crystal Palace     1.064257   1.289157
Derby              1.180451   1.330827
Everton            1.517422   1.114983
Fulham             1.351974   1.289474
Huddersfield       0.684211   1.473684
Hull               1.126316   1.526316
Ipswich            1.200000   1.312500
Leeds              1.444444   1.148148
Leicester          1.409231   1.280000
Liverpool          2.022648   0.796167
Man City           2.060543   0.939457
Man United         2.109756   0.738676
Middlesbrough      1.353383   1.233083
Newcastle          1.617537   1.128731
Norwich            1.194286   1.485714
Nott'm Forest      1.288660   1.206186
Oldham             1.142857   1.571429
Portsmouth         1.383459   1.195489
QPR                1.296610   1.338983
Reading            1.245614   1.368421
Sheffield United   1.076923   1.102564
Sheffield Weds     1.459854   1.175182
Southampton        1.399093   1.265306
Stoke              1.305263   1.121053
Sunderland         1.105263   1.220395
Swansea            1.345865   1.278195
Swindon            1.190476   2.142857
Tottenham          1.728223   1.076655
Watford            1.184211   1.552632
West Brom          1.194332   1.461538
West Ham           1.462282   1.274662
Wigan              1.111842   1.414474
Wimbledon          1.357664   1.277372
Wolves             1.169591   1.403509

HomeTeam
Man United          1211
Arsenal             1182
Liverpool           1161
Chelsea             1112
Tottenham            992
Man City             987
Everton              871
Newcastle            867
West Ham             756
Aston Villa          681
Southampton          617
Blackburn            507
Leicester            458
Fulham               411
Leeds                390
Middlesbrough        360
Sunderland           336
Bolton               319
West Brom            295
Crystal Palace       265
Stoke                248
Norwich              209
Sheffield Weds       200
Wolves               200
Charlton             199
Coventry             190
Wimbledon            186
Portsmouth           184
Watford              180
Swansea              179
Wigan                169
Birmingham           162
Burnley              161
Derby                157
Bournemouth          156
QPR                  153
Brighton             141
Nott'm Forest        125
Hull                 107
Ipswich               96
Sheffield United      84
Reading               71
Brentford             57
Bradford              46
Cardiff               41
Blackpool             30
Huddersfield          26
Swindon               25
Barnsley              25
Oldham                24
Name: HomeGoals, dtype: int64

HomeTeam
Arsenal             574
Aston Villa         517
Barnsley             19
Birmingham          133
Blackburn           327
Blackpool            19
Bolton              247
Bournemouth         114
Bradford             38
Brentford            38
Brighton            114
Burnley             152
Cardiff              38
Charlton            152
Chelsea             574
Coventry            156
Crystal Palace      249
Derby               133
Everton             574
Fulham              304
Huddersfield         38
Hull                 95
Ipswich              80
Leeds               270
Leicester           325
Liverpool           574
Man City            479
Man United          574
Middlesbrough       266
Newcastle           536
Norwich             175
Nott'm Forest        97
Oldham               21
Portsmouth          133
QPR                 118
Reading              57
Sheffield United     78
Sheffield Weds      137
Southampton         441
Stoke               190
Sunderland          304
Swansea             133
Swindon              21
Tottenham           574
Watford             152
West Brom           247
West Ham            517
Wigan               152
Wimbledon           137
Wolves              171
Name: count, dtype: int64

In [5]:
# Data merging and joining (especially useful when you are working with large amounts of data)
import pandas as pd
df = pd.read_csv(r'C:\Users\16254\Desktop\numpy & pandas\English Premier League.csv')

new_df = pd.DataFrame(columns = df.columns)  # Initialize an empty DataFrame with the same columns.

for chunk_df in pd.read_csv(r'C:\Users\16254\Desktop\numpy & pandas\English Premier League.csv', chunksize = 5):
    #print(chunk_df)
    results = chunk_df.groupby(['HomeTeam'])['HomeGoals'].count()  
    new_df = pd.concat([new_df, results])  # Concatenate the current results to the new_df DataFrame

# Reset index for new_df to avoid index duplication
new_df.reset_index(inplace = True)

print(new_df,'\n')


# Fillna to replace all NaN
filled_df = new_df.fillna('None')
print(filled_df, '\n')

# Fillna on one column
filled_df['Result'] = new_df['Result'].fillna(0)
print(filled_df, '\n')

# Fillna on multiple columns
filled_df[['League', 'Date']] = new_df[['League','Date']].fillna('unknown')
print(filled_df, '\n')

filled_df = new_df.fillna(value = {'League': 'EPL', 'Date': 'unknown'})
print(filled_df, '\n')

             index League Date HomeTeam AwayTeam HomeGoals AwayGoals Result
0          Arsenal    NaN  NaN      NaN      NaN         1       NaN    NaN
1      Aston Villa    NaN  NaN      NaN      NaN         1       NaN    NaN
2          Chelsea    NaN  NaN      NaN      NaN         1       NaN    NaN
3        Liverpool    NaN  NaN      NaN      NaN         1       NaN    NaN
4         Man City    NaN  NaN      NaN      NaN         1       NaN    NaN
...            ...    ...  ...      ...      ...       ...       ...    ...
11460      Everton    NaN  NaN      NaN      NaN         1       NaN    NaN
11461        Leeds    NaN  NaN      NaN      NaN         1       NaN    NaN
11462    Leicester    NaN  NaN      NaN      NaN         1       NaN    NaN
11463   Man United    NaN  NaN      NaN      NaN         1       NaN    NaN
11464  Southampton    NaN  NaN      NaN      NaN         1       NaN    NaN

[11465 rows x 8 columns]

             index League  Date HomeTeam AwayTeam  HomeGoals AwayGoals Result
0          Arsenal   None  None     None     None          1      None   None
1      Aston Villa   None  None     None     None          1      None   None
2          Chelsea   None  None     None     None          1      None   None
3        Liverpool   None  None     None     None          1      None   None
4         Man City   None  None     None     None          1      None   None
...            ...    ...   ...      ...      ...        ...       ...    ...
11460      Everton   None  None     None     None          1      None   None
11461        Leeds   None  None     None     None          1      None   None
11462    Leicester   None  None     None     None          1      None   None
11463   Man United   None  None     None     None          1      None   None
11464  Southampton   None  None     None     None          1      None   None

[11465 rows x 8 columns]

             index League  Date HomeTeam AwayTeam  HomeGoals AwayGoals  Result
0          Arsenal   None  None     None     None          1      None       0
1      Aston Villa   None  None     None     None          1      None       0
2          Chelsea   None  None     None     None          1      None       0
3        Liverpool   None  None     None     None          1      None       0
4         Man City   None  None     None     None          1      None       0
...            ...    ...   ...      ...      ...        ...       ...     ...
11460      Everton   None  None     None     None          1      None       0
11461        Leeds   None  None     None     None          1      None       0
11462    Leicester   None  None     None     None          1      None       0
11463   Man United   None  None     None     None          1      None       0
11464  Southampton   None  None     None     None          1      None       0

[11465 rows x 8 columns]

             index   League     Date HomeTeam AwayTeam  HomeGoals AwayGoals  \
0          Arsenal  unknown  unknown     None     None          1      None
1      Aston Villa  unknown  unknown     None     None          1      None
2          Chelsea  unknown  unknown     None     None          1      None
3        Liverpool  unknown  unknown     None     None          1      None
4         Man City  unknown  unknown     None     None          1      None
...            ...      ...      ...      ...      ...        ...       ...
11460      Everton  unknown  unknown     None     None          1      None
11461        Leeds  unknown  unknown     None     None          1      None
11462    Leicester  unknown  unknown     None     None          1      None
11463   Man United  unknown  unknown     None     None          1      None
11464  Southampton  unknown  unknown     None     None          1      None

       Result
0           0
1           0
2           0
3           0
4           0
...       ...
11460       0
11461       0
11462       0
11463       0
11464       0

[11465 rows x 8 columns]

             index League     Date HomeTeam AwayTeam HomeGoals AwayGoals  \
0          Arsenal    EPL  unknown      NaN      NaN         1       NaN
1      Aston Villa    EPL  unknown      NaN      NaN         1       NaN
2          Chelsea    EPL  unknown      NaN      NaN         1       NaN
3        Liverpool    EPL  unknown      NaN      NaN         1       NaN
4         Man City    EPL  unknown      NaN      NaN         1       NaN
...            ...    ...      ...      ...      ...       ...       ...
11460      Everton    EPL  unknown      NaN      NaN         1       NaN
11461        Leeds    EPL  unknown      NaN      NaN         1       NaN
11462    Leicester    EPL  unknown      NaN      NaN         1       NaN
11463   Man United    EPL  unknown      NaN      NaN         1       NaN
11464  Southampton    EPL  unknown      NaN      NaN         1       NaN

      Result
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
...      ...
11460    NaN
11461    NaN
11462    NaN
11463    NaN
11464    NaN

[11465 rows x 8 columns]

C:\Users\16254\AppData\Local\Temp\ipykernel_56860\539205592.py:19: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  filled_df = new_df.fillna('None')
C:\Users\16254\AppData\Local\Temp\ipykernel_56860\539205592.py:23: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  filled_df['Result'] = new_df['Result'].fillna(0)