In [3]:
# create a DataFrame
#from a dictionary
import pandas as pd
data = {
    'fruit':['apple', 'banana', 'strawberry'], 
    'vegetable': ['tomato', 'potato', 'cucumber'], 
    'drinks': ['milk', 'juice', 'cocktail']
}
index_labels = ['r1', 'r2', 'r3']
df = pd.DataFrame(data, index = index_labels)
print(df)

#from a numpy array
import numpy as np
data_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df_array = pd.DataFrame(data_array)
print(df_array)

# The pd.DataFrame() method expects a data dictionary or array-like structure.

         fruit vegetable    drinks
r1       apple    tomato      milk
r2      banana    potato     juice
r3  strawberry  cucumber  cocktail
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
# Reading data
import pandas as pd

df = pd.read_csv(r"C:\Users\16254\Desktop\numpy & pandas\English Premier League.csv")

print(df.head(),'\n')
print(df.tail(3),'\n')

#Read head
print(df.columns, '\n') # df.columns get the pandas DataFrame column names as a list 

#Read each column
print(df['HomeTeam'], '\n')
print(df[['HomeGoals', 'AwayGoals']], '\n')

#Read each row
print(df.iloc[2:5], '\n')

''' iterrows() 是一个生成器，它产生 (index,row) 对，其中 index 是行索引， row 是表示该行数据的 pandas Series。
for index, row in df.iterrows():
    print(index, row)
    遍历所有行'''

# df.loc[...]用于根据布尔条件来过滤行
arsenal_games = df.loc[df['HomeTeam'] == 'Arsenal']
print(arsenal_games, '\n')  # This will give you a DataFrame that contains only the rows where the HomeTeam is 'Arsenal'

# Filter rows based on multiple conditions
filtered_df = df.loc[(df['HomeTeam'] == 'Arsenal') & (df['HomeGoals'] > 1)]
print(filtered_df, '\n')

# Read a specific location(R,C)
print(df.iloc[3,2])

                   League      Date     HomeTeam        AwayTeam  HomeGoals  \
0  English Premier League  14/08/93      Arsenal        Coventry          0
1  English Premier League  14/08/93  Aston Villa             QPR          4
2  English Premier League  14/08/93      Chelsea       Blackburn          1
3  English Premier League  14/08/93    Liverpool  Sheffield Weds          2
4  English Premier League  14/08/93     Man City           Leeds          1

   AwayGoals Result
0          3      A
1          1      H
2          2      A
3          0      H
4          1      D

                       League        Date     HomeTeam   AwayTeam  HomeGoals  \
11561  English Premier League  28/05/2023    Leicester   West Ham          2
11562  English Premier League  28/05/2023   Man United     Fulham          2
11563  English Premier League  28/05/2023  Southampton  Liverpool          4

       AwayGoals Result
11561          1      H
11562          1      H
11563          4      D

Index(['League', 'Date', 'HomeTeam', 'AwayTeam', 'HomeGoals', 'AwayGoals',
       'Result'],
      dtype='object')

0            Arsenal
1        Aston Villa
2            Chelsea
3          Liverpool
4           Man City
            ...
11559        Everton
11560          Leeds
11561      Leicester
11562     Man United
11563    Southampton
Name: HomeTeam, Length: 11564, dtype: object

       HomeGoals  AwayGoals
0              0          3
1              4          1
2              1          2
3              2          0
4              1          1
...          ...        ...
11559          1          0
11560          1          4
11561          2          1
11562          2          1
11563          4          4

[11564 rows x 2 columns]

                   League      Date   HomeTeam        AwayTeam  HomeGoals  \
2  English Premier League  14/08/93    Chelsea       Blackburn          1
3  English Premier League  14/08/93  Liverpool  Sheffield Weds          2
4  English Premier League  14/08/93   Man City           Leeds          1

   AwayGoals Result
2          2      A
3          0      H
4          1      D

                       League        Date HomeTeam     AwayTeam  HomeGoals  \
0      English Premier League    14/08/93  Arsenal     Coventry          0
34     English Premier League    24/08/93  Arsenal        Leeds          2
45     English Premier League    28/08/93  Arsenal      Everton          2
66     English Premier League    11/09/93  Arsenal      Ipswich          4
88     English Premier League    25/09/93  Arsenal  Southampton          1
...                       ...         ...      ...          ...        ...
11455  English Premier League  01/04/2023  Arsenal        Leeds          4
11490  English Premier League  21/04/2023  Arsenal  Southampton          3
11517  English Premier League  02/05/2023  Arsenal      Chelsea          3
11539  English Premier League  14/05/2023  Arsenal     Brighton          0
11554  English Premier League  28/05/2023  Arsenal       Wolves          5

       AwayGoals Result
0              3      A
34             1      H
45             0      H
66             0      H
88             0      H
...          ...    ...
11455          1      H
11490          3      D
11517          1      H
11539          3      A
11554          0      H

[574 rows x 7 columns]

                       League        Date HomeTeam          AwayTeam  \
34     English Premier League    24/08/93  Arsenal             Leeds
45     English Premier League    28/08/93  Arsenal           Everton
66     English Premier League    11/09/93  Arsenal           Ipswich
175    English Premier League    27/11/93  Arsenal         Newcastle
240    English Premier League    29/12/93  Arsenal  Sheffield United
...                       ...         ...      ...               ...
11453  English Premier League  19/03/2023  Arsenal    Crystal Palace
11455  English Premier League  01/04/2023  Arsenal             Leeds
11490  English Premier League  21/04/2023  Arsenal       Southampton
11517  English Premier League  02/05/2023  Arsenal           Chelsea
11554  English Premier League  28/05/2023  Arsenal            Wolves

       HomeGoals  AwayGoals Result
34             2          1      H
45             2          0      H
66             4          0      H
175            2          1      H
240            3          0      H
...          ...        ...    ...
11453          4          1      H
11455          4          1      H
11490          3          3      D
11517          3          1      H
11554          5          0      H

[352 rows x 7 columns]

Liverpool

In [7]:
# Sorting/Describing data
import pandas as pd

df = pd.read_csv(r"C:\Users\16254\Desktop\numpy & pandas\English Premier League.csv")

print(df.describe(), '\n')

print(df.sort_values('HomeTeam'), '\n')

print(df.sort_values('HomeGoals', ascending = False))

          HomeGoals     AwayGoals
count  11564.000000  11564.000000
mean       1.522743      1.145019
std        1.306091      1.138957
min        0.000000      0.000000
25%        1.000000      0.000000
50%        1.000000      1.000000
75%        2.000000      2.000000
max        9.000000      9.000000

                       League        Date HomeTeam    AwayTeam  HomeGoals  \
0      English Premier League    14/08/93  Arsenal    Coventry          0
5571   English Premier League   2020/10/7  Arsenal      Bolton          2
5563   English Premier League   2007/10/7  Arsenal  Sunderland          3
5541   English Premier League    2022/9/7  Arsenal       Derby          5
5528   English Premier League    2002/9/7  Arsenal  Portsmouth          3
...                       ...         ...      ...         ...        ...
7158   English Premier League  2017/12/11   Wolves       Stoke          1
9770   English Premier League  03/11/2018   Wolves   Tottenham          2
10441  English Premier League  21/09/2020   Wolves    Man City          1
4200   English Premier League    2007/2/4   Wolves     Arsenal          1
4318   English Premier League    2001/5/4   Wolves     Everton          2

       AwayGoals Result
0              3      A
5571           0      H
5563           2      H
5541           0      H
5528           1      H
...          ...    ...
7158           2      A
9770           3      A
10441          3      A
4200           3      A
4318           1      H

[11564 rows x 7 columns]

                       League        Date    HomeTeam        AwayTeam  \
787    English Premier League    04/03/95  Man United         Ipswich
6370   English Premier League   2022/11/9   Tottenham           Wigan
11218  English Premier League  27/08/2022   Liverpool     Bournemouth
10631  English Premier League  02/02/2021  Man United     Southampton
2518   English Premier League    19/09/99   Newcastle  Sheffield Weds
...                       ...         ...         ...             ...
2689   English Premier League    13/02/00     Arsenal       Liverpool
8008   English Premier League   2008/2/14     Norwich        Man City
5605   English Premier League   2011/11/7      Bolton   Middlesbrough
6731   English Premier League  2007/11/10     Arsenal       Newcastle
0      English Premier League    14/08/93     Arsenal        Coventry

       HomeGoals  AwayGoals Result
787            9          0      H
6370           9          1      H
11218          9          0      H
10631          9          0      H
2518           8          0      H
...          ...        ...    ...
2689           0          1      A
8008           0          0      D
5605           0          0      D
6731           0          1      A
0              0          3      A

[11564 rows x 7 columns]

In [11]:
# Now let's just feel free to do what we really wanna do!!
# I wanna fliter all the matches of Liverpool and sort the Goals in a descending order.(Yeah I LOOOOVE Liverpool!)

import pandas as pd
df = pd.read_csv(r'C:\Users\16254\Desktop\numpy & pandas\English Premier League.csv')

liverpool_df = df.loc[(df['HomeTeam'] == 'Liverpool') & (df['HomeGoals'] > 0)]
sort_values = liverpool_df.sort_values('HomeGoals', ascending = False)
print(sort_values)

                       League        Date   HomeTeam        AwayTeam  \
11218  English Premier League  27/08/2022  Liverpool     Bournemouth
2278   English Premier League    16/01/99  Liverpool     Southampton
11433  English Premier League  05/03/2023  Liverpool      Man United
6303   English Premier League    2026/9/9  Liverpool            Hull
9012   English Premier League  2006/11/16  Liverpool         Watford
...                       ...         ...        ...             ...
3946   English Premier League  03/05/2003  Liverpool        Man City
8621   English Premier League  25/10/2015  Liverpool     Southampton
8643   English Premier League  08/11/2015  Liverpool  Crystal Palace
8660   English Premier League  29/11/2015  Liverpool         Swansea
11545  English Premier League  20/05/2023  Liverpool     Aston Villa

       HomeGoals  AwayGoals Result
11218          9          0      H
2278           7          1      H
11433          7          0      H
6303           6          1      H
9012           6          1      H
...          ...        ...    ...
3946           1          2      A
8621           1          1      D
8643           1          2      A
8660           1          0      H
11545          1          1      D

[491 rows x 7 columns]